name: CI

on:
  push:
    branches: [master, develop, release/**, feature/**]

jobs:
  test-build-deploy-to-production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.16.2"

      - run: npm install

      - name: Run unit test
        run: npm run test:github-ci

      - name: Run e2e test
        run: |
          node /home/runner/work/corona-tracker/corona-tracker/node_modules/protractor/bin/webdriver-manager clean
          node /home/runner/work/corona-tracker/corona-tracker/node_modules/protractor/bin/webdriver-manager update --versions.chrome=81.0.4044.138
          npm run e2e:github-ci

      - name: Build
        run: npm run build

      - name: Deploy to Firebase
        uses: lowply/deploy-firebase@v0.0.2
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_CI }}
          FIREBASE_PROJECT: corona-tracker-7b96f
